-- CreateEnum
CREATE TYPE "NotificationType" AS ENUM ('SUBMISSION_APPROVED', 'SUBMISSION_REJECTED', 'SUBMISSION_SUBMITTED', 'SUBMISSION_EDITED', 'SUBMISSION_DELETED', 'SUBMISSION_OPPONENT_ASSIGNED', 'ASSIGNMENT_PICKED', 'ASSIGNMENT_UNPICKED', 'REVIEW_CREATED', 'REVIEW_EDITED', 'REVIEW_DELETED', 'FILE_MAIN_UPLOADED', 'FILE_ATTACHMENT_UPLOADED', 'FILE_UPLOADED', 'FILE_MAIN_EDITED', 'FILE_ATTACHMENT_EDITED', 'FILE_EDITED', 'FILE_MAIN_DELETED', 'FILE_ATTACHMENT_DELETED', 'FILE_DELETED');

-- CreateTable
CREATE TABLE "Notification" (
    "id" TEXT NOT NULL,
    "type" "NotificationType" NOT NULL,
    "message" TEXT NOT NULL,
    "read" BOOLEAN NOT NULL DEFAULT false,
    "entityType" TEXT,
    "entityId" TEXT,
    "recipientId" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "Notification_pkey" PRIMARY KEY ("id")
);

-- AddForeignKey
ALTER TABLE "Notification" ADD CONSTRAINT "Notification_recipientId_fkey" FOREIGN KEY ("recipientId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
